Once the data was imported successfully, it was graphed. This graph
shows the diabetic's highs and lows over several days in June. Deltas
in blood glucose levels shown below are more dramatic that those shown
by the Nightscout project. The Nightscout project normalizes the data
by first taking the log of the Y-Axis values. The graph below shows
the raw values.



```{r simple-graph, echo=TRUE}

entries %>%
    filter(date >= '2015-06-17' & date <= '2015-07-17') %>%
    select(date, sgv) %>%
    ggplot(data=., aes(x = date, y=sgv)) +
    geom_point() +
    geom_smooth() +
    geom_line() +
    labs(x="Date / Time", y="Sensor Glucose Values(SGV)",
         title="Sensor Glucose Values Over Time")
       
```

```{r simple-graph-2, echo=TRUE}

entries %>%
    filter(date >= '2015-06-20' & date <= '2015-07-20') %>%
    select(date, sgv) %>%
    ggplot(data=., aes(x = date, y=sgv)) +
        geom_point() +
        geom_line() +
        labs(x="Date / Time", y="Sensor Glucose Values(SGV)",
             title="Sensor Glucose Values Over Time")
       
```
